repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: [--ignore-words=ignore_words.txt]
    exclude: >
        (?x)^(
            .*\.csv
        )$
